port: 8080

db:
  connection-string: basemall?parseTime=true&charset=utf8mb4,utf8
  ip: 127.0.0.1
  port: 3306
  username: root
  password: Jarvan1110
  max-connection: 10
  max-idle-connection: 5
  max-connection-lifetime: 3 # mins

redis:
  ip: 127.0.0.1
  port: 6379
  password: